// © 2026 Nokia
// Licensed under the MIT License
// SPDX-License-Identifier: MIT

package io.jenkins.plugins.interactiveinput.rest;

import edu.umd.cs.findbugs.annotations.NonNull;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import org.kohsuke.stapler.HttpResponse;
import org.kohsuke.stapler.StaplerRequest2;
import org.kohsuke.stapler.StaplerResponse2;

/**
 * Serves an {@code interactiveView} HTML snapshot for display <em>inside a sandboxed frame</em>, so a
 * reviewer can look at a generated report (a Robot Framework {@code log.html}, an Allure/pytest report,
 * …) instead of only its escaped source.
 *
 * <p>The content is generated by a pipeline and is therefore untrusted, so the whole point of this class
 * is the header set below. It is the counterpart of {@link DownloadHttpResponse}, which serves the same
 * bytes as an {@code attachment} precisely so that a browser never renders them in the Jenkins origin.
 *
 * <h2>Why {@code Content-Security-Policy: sandbox}</h2>
 *
 * <p>{@code sandbox allow-scripts} applies the {@code <iframe sandbox>} rules to <em>this</em> document.
 * Because {@code allow-same-origin} is deliberately absent, the browser gives the document a unique
 * <em>opaque</em> origin, which means its scripts:
 *
 * <ul>
 *   <li>cannot reach the embedding Jenkins page's DOM (it is cross-origin to them);
 *   <li>cannot read the session cookie, {@code localStorage} or {@code sessionStorage};
 *   <li>cannot read a CSRF crumb — Jenkins sends no CORS headers, so a cross-origin read is refused —
 *       and therefore cannot forge an authenticated mutating request; and
 *   <li>cannot submit a form, open a window, or navigate the reviewer's tab, since {@code allow-forms},
 *       {@code allow-popups} and {@code allow-top-navigation} are all withheld.
 * </ul>
 *
 * <p>Sending it as a <em>header</em> (rather than relying only on the frame's {@code sandbox} attribute)
 * is what makes the endpoint safe to open directly: pasting the URL into the address bar still yields an
 * opaque-origin document, so it cannot script the Jenkins origin either way. The frame adds the same
 * {@code sandbox} attribute, giving two independent enforcement points.
 *
 * <p>Scripts are permitted on purpose: report generators embed their entire payload as JavaScript, so a
 * script-free render shows nothing useful (a Robot {@code log.html} degrades to its "JavaScript
 * disabled" error). The residual risk of {@code allow-scripts} — outbound requests, and misleading
 * content drawn inside the frame — is bounded by the opaque origin and accepted for content the
 * operator's own pipeline produced; an operator who disagrees turns the {@code htmlRendering} feature
 * off and keeps HTML source-only.
 *
 * <p>No other CSP directive is set: a self-contained report relies on inline {@code <script>}, inline
 * {@code <style>} and {@code data:} URIs, so a {@code default-src}/{@code script-src} restriction here
 * would break the very files this exists to display. {@code frame-ancestors 'self'} keeps another site
 * from embedding the endpoint, and {@code nosniff} plus an explicit charset stop MIME/encoding
 * guessing.
 */
public class SandboxedHtmlResponse implements HttpResponse {

    /**
     * The isolation policy. {@code sandbox allow-scripts} yields an opaque origin that can still run the
     * report's own JavaScript; the remaining directives are the hardening from core's page policy that a
     * self-contained report does not need: no {@code <base>} hijacking, no form submission, and only
     * Jenkins itself may frame the document.
     *
     * <p>Deliberately absent are {@code default-src} / {@code script-src} / {@code style-src} /
     * {@code img-src}: a generated report carries inline {@code <script>}, inline {@code <style>} and
     * {@code data:} URIs, so restricting those is what leaves it blank.
     */
    static final String CSP = "sandbox allow-scripts; base-uri 'none'; form-action 'none'; "
            + "frame-ancestors 'self'";

    @NonNull
    private final byte[] body;

    /**
     * @param html the snapshot's HTML source (serialised as UTF-8, which the {@code charset} below
     *     declares so the browser never has to guess the encoding)
     */
    public SandboxedHtmlResponse(@NonNull String html) {
        this.body = html.getBytes(StandardCharsets.UTF_8);
    }

    @Override
    public void generateResponse(StaplerRequest2 req, StaplerResponse2 rsp, Object node) throws IOException {
        rsp.setStatus(200);
        rsp.setContentType("text/html;charset=UTF-8");
        // setHeader, NOT addHeader: core's CSP decorator has already added its page policy to this
        // response, and a browser enforces EVERY Content-Security-Policy header it receives (the
        // intersection). Appending ours would therefore leave core's script-src 'self' in force and
        // silently block the report's inline scripts — the blank page this class exists to avoid. Core's
        // policy assumes a trusted same-origin page; this response is the opposite (untrusted content in
        // an opaque origin), so replacing it with the sandbox policy above is the stricter choice where
        // it matters: the document cannot reach the Jenkins origin at all.
        rsp.setHeader("Content-Security-Policy", CSP);
        // Older engines honour only the prefixed forms; harmless where the standard header is understood.
        rsp.setHeader("X-Content-Security-Policy", CSP);
        rsp.setHeader("X-WebKit-CSP", CSP);
        rsp.setHeader("X-Content-Type-Options", "nosniff");
        rsp.setHeader("Cache-Control", "no-store");
        rsp.setContentLength(body.length);
        rsp.getOutputStream().write(body);
    }
}
